# Generated by Django 5.2.6 on 2025-09-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.RemoveField(
            model_name='account',
            name='booking_credit',
        ),
    ]
