# Generated by Django 5.2.6 on 2025-09-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.TextField()),
                ('roomsize', models.TextField()),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('roomnumber', models.TextField()),
                ('roomsize', models.TextField()),
                ('time', models.TextField()),
                ('date', models.TextField()),
            ],
            options={
                'db_table': 'reserve',
            },
        ),
    ]
