# Generated by Django 5.2.6 on 2025-09-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_classroom_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.AddField(
            model_name='classroom',
            name='roomcapacity',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='stop_time',
            field=models.TextField(default='0'),
        ),
    ]
