# Generated by Django 5.2.6 on 2025-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('password', models.TextField()),
                ('booking_credit', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('size', models.TextField()),
                ('occupied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
