# Generated by Django 5.2.6 on 2025-09-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'manager_account',
            },
        ),
    ]
